/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.course.fundamental.basicjava;

/**
 *
 * @author Pulung
 */
public class Kalkulator2 extends javax.swing.JFrame {

    private boolean newNumber = true;
    private float lastInput;
    private char operator = ' ';

    /**
     * Creates new form Kalkulator2
     */
    public Kalkulator2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelDisplay = new javax.swing.JLabel();
        labelHistory = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buttonMemClear = new javax.swing.JButton();
        buttonMemRecall = new javax.swing.JButton();
        buttonMemAdd = new javax.swing.JButton();
        buttonMemSub = new javax.swing.JButton();
        buttonPercent = new javax.swing.JButton();
        buttonClearExisting = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        buttonBackspace = new javax.swing.JButton();
        buttonSeven = new javax.swing.JButton();
        buttonEight = new javax.swing.JButton();
        buttonNine = new javax.swing.JButton();
        buttonDivide = new javax.swing.JButton();
        buttonFour = new javax.swing.JButton();
        buttonFive = new javax.swing.JButton();
        buttonSix = new javax.swing.JButton();
        buttonMultiply = new javax.swing.JButton();
        buttonOne = new javax.swing.JButton();
        buttonTwo = new javax.swing.JButton();
        buttonThree = new javax.swing.JButton();
        buttonSubtract = new javax.swing.JButton();
        buttonNegate = new javax.swing.JButton();
        buttonZero = new javax.swing.JButton();
        buttonEqual = new javax.swing.JButton();
        buttonPlus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        labelDisplay.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        labelDisplay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDisplay.setText("0");
        jPanel1.add(labelDisplay, java.awt.BorderLayout.SOUTH);

        labelHistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelHistory.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelHistory.setText(" ");
        labelHistory.setToolTipText("");
        jPanel1.add(labelHistory, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(6, 4, 2, 2));

        buttonMemClear.setText("MC");
        jPanel2.add(buttonMemClear);

        buttonMemRecall.setText("MR");
        jPanel2.add(buttonMemRecall);

        buttonMemAdd.setText("M+");
        jPanel2.add(buttonMemAdd);

        buttonMemSub.setText("M-");
        jPanel2.add(buttonMemSub);

        buttonPercent.setText("%");
        jPanel2.add(buttonPercent);

        buttonClearExisting.setText("CE");
        jPanel2.add(buttonClearExisting);

        buttonClear.setText("C");
        jPanel2.add(buttonClear);

        buttonBackspace.setText("<=");
        buttonBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackspaceActionPerformed(evt);
            }
        });
        jPanel2.add(buttonBackspace);

        buttonSeven.setText("7");
        buttonSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSevenActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSeven);

        buttonEight.setText("8");
        buttonEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEightActionPerformed(evt);
            }
        });
        jPanel2.add(buttonEight);

        buttonNine.setText("9");
        buttonNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNineActionPerformed(evt);
            }
        });
        jPanel2.add(buttonNine);

        buttonDivide.setText("/");
        buttonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivideActionPerformed(evt);
            }
        });
        jPanel2.add(buttonDivide);

        buttonFour.setText("4");
        buttonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFourActionPerformed(evt);
            }
        });
        jPanel2.add(buttonFour);

        buttonFive.setText("5");
        buttonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiveActionPerformed(evt);
            }
        });
        jPanel2.add(buttonFive);

        buttonSix.setText("6");
        buttonSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSixActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSix);

        buttonMultiply.setText("*");
        buttonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultiplyActionPerformed(evt);
            }
        });
        jPanel2.add(buttonMultiply);

        buttonOne.setText("1");
        buttonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOneActionPerformed(evt);
            }
        });
        jPanel2.add(buttonOne);

        buttonTwo.setText("2");
        buttonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTwoActionPerformed(evt);
            }
        });
        jPanel2.add(buttonTwo);

        buttonThree.setText("3");
        buttonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThreeActionPerformed(evt);
            }
        });
        jPanel2.add(buttonThree);

        buttonSubtract.setText("-");
        buttonSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubtractActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSubtract);

        buttonNegate.setText("+/-");
        buttonNegate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNegateActionPerformed(evt);
            }
        });
        jPanel2.add(buttonNegate);

        buttonZero.setText("0");
        buttonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZeroActionPerformed(evt);
            }
        });
        jPanel2.add(buttonZero);

        buttonEqual.setText("=");
        buttonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEqualActionPerformed(evt);
            }
        });
        jPanel2.add(buttonEqual);

        buttonPlus.setText("+");
        buttonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlusActionPerformed(evt);
            }
        });
        jPanel2.add(buttonPlus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZeroActionPerformed
        // TODO add your handling code here:
        addToDisplay("0");
    }//GEN-LAST:event_buttonZeroActionPerformed

    private void buttonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOneActionPerformed
        addToDisplay("1");
    }//GEN-LAST:event_buttonOneActionPerformed

    private void buttonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTwoActionPerformed
        // TODO add your handling code here:
        addToDisplay("2");
    }//GEN-LAST:event_buttonTwoActionPerformed

    private void buttonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThreeActionPerformed
        // TODO add your handling code here:
        addToDisplay("3");
    }//GEN-LAST:event_buttonThreeActionPerformed

    private void buttonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFourActionPerformed
        addToDisplay("4");
    }//GEN-LAST:event_buttonFourActionPerformed

    private void buttonFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFiveActionPerformed
        addToDisplay("5");
    }//GEN-LAST:event_buttonFiveActionPerformed

    private void buttonSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSixActionPerformed
        addToDisplay("6");
    }//GEN-LAST:event_buttonSixActionPerformed

    private void buttonSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSevenActionPerformed
        addToDisplay("7");
    }//GEN-LAST:event_buttonSevenActionPerformed

    private void buttonEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEightActionPerformed
        addToDisplay("8");
    }//GEN-LAST:event_buttonEightActionPerformed

    private void buttonNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNineActionPerformed
        addToDisplay("9");
    }//GEN-LAST:event_buttonNineActionPerformed

    private void buttonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivideActionPerformed
        newNumber = true;
        lastInput = Float.parseFloat(labelDisplay.getText());
        operator = '/';
        labelHistory.setText(labelDisplay.getText() + " / ");
    }//GEN-LAST:event_buttonDivideActionPerformed

    private void buttonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultiplyActionPerformed
        newNumber = true;
        lastInput = Float.parseFloat(labelDisplay.getText());
        operator = 'x';
        labelHistory.setText(labelDisplay.getText() + " x ");
    }//GEN-LAST:event_buttonMultiplyActionPerformed

    private void buttonSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubtractActionPerformed
        newNumber = true;
        lastInput = Float.parseFloat(labelDisplay.getText());
        operator = '-';
        labelHistory.setText(labelDisplay.getText() + " - ");
    }//GEN-LAST:event_buttonSubtractActionPerformed

    private void buttonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlusActionPerformed
        newNumber = true;
        lastInput = Float.parseFloat(labelDisplay.getText());
        operator = '+';
        labelHistory.setText(labelDisplay.getText() + " + ");
    }//GEN-LAST:event_buttonPlusActionPerformed

    private void buttonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEqualActionPerformed
        float number = Float.parseFloat(labelDisplay.getText());
        float result = 0;
        switch(operator) {
            case '+':
                result = lastInput + number;
                break;
            case '-':
                result = lastInput - number;
                break;
            case 'x':
                result = lastInput * number;
                break;
            case '/':
                result = lastInput / number;
                break;
            default:
                break;
        }
        labelHistory.setText(labelHistory.getText() + labelDisplay.getText() + " = ");
        labelDisplay.setText(String.valueOf(result));
        newNumber = true;
        lastInput = number;
    }//GEN-LAST:event_buttonEqualActionPerformed

    private void buttonNegateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNegateActionPerformed
        if (labelDisplay.getText().charAt(0) == '-') {
            labelDisplay.setText(labelDisplay.getText().replace('-', ' ').trim());
        } else {
            labelDisplay.setText("-" + labelDisplay.getText());
        }
    }//GEN-LAST:event_buttonNegateActionPerformed

    private void buttonBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackspaceActionPerformed
        int lenDisplay = labelDisplay.getText().length();
        if (lenDisplay == 1 || (lenDisplay == 2 && labelDisplay.getText().charAt(0) == '-') ) {
            labelDisplay.setText("0");
        } else {
            labelDisplay.setText(labelDisplay.getText().substring(0, lenDisplay - 1));
        }
    }//GEN-LAST:event_buttonBackspaceActionPerformed

    public void addToDisplay(String digit) {
        if (labelDisplay.getText().equals("0") || newNumber == true) {
            labelDisplay.setText(digit);
            newNumber = false;
        } else {
            labelDisplay.setText(labelDisplay.getText() + digit);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBackspace;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonClearExisting;
    private javax.swing.JButton buttonDivide;
    private javax.swing.JButton buttonEight;
    private javax.swing.JButton buttonEqual;
    private javax.swing.JButton buttonFive;
    private javax.swing.JButton buttonFour;
    private javax.swing.JButton buttonMemAdd;
    private javax.swing.JButton buttonMemClear;
    private javax.swing.JButton buttonMemRecall;
    private javax.swing.JButton buttonMemSub;
    private javax.swing.JButton buttonMultiply;
    private javax.swing.JButton buttonNegate;
    private javax.swing.JButton buttonNine;
    private javax.swing.JButton buttonOne;
    private javax.swing.JButton buttonPercent;
    private javax.swing.JButton buttonPlus;
    private javax.swing.JButton buttonSeven;
    private javax.swing.JButton buttonSix;
    private javax.swing.JButton buttonSubtract;
    private javax.swing.JButton buttonThree;
    private javax.swing.JButton buttonTwo;
    private javax.swing.JButton buttonZero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelDisplay;
    private javax.swing.JLabel labelHistory;
    // End of variables declaration//GEN-END:variables
}
